fix: linting gcp-tools
ssc-spc-ccoe-cei/gcp-tools pull request #23
Opened 2023-03-30 17:58 UTC by danielsvensson-ssc

* Resolved ~88 style issues identified across ~7 markdown files
* Introduced ‘shell’ for all fenced-code-language blocks containing code
* Corrected spelling error, outside code and resource names
* Updated .markdown-lint-config.yaml - MD012 (CHANGELOG.md workaround), MD013 (line length) and (MD40 fenced code blocks)

2023-03-30 20:32 UTC, seanwilkens-ssc submitted a review, later dismissed

2023-03-31 12:38 UTC, davelanglois-ssc requested changes

2023-03-31 12:38 UTC, davelanglois-ssc commented on CHANGELOG.md
let's exclude changelog.md from the linting rule. it is generated by release-please

2023-03-31 12:38 UTC, davelanglois-ssc commented on devcontainer/doc/README.md
> +```shell
just curious to understand why shell has been chosen knowing that it is a powershell block

2023-04-04 11:19 UTC, danielsvensson-ssc commented on CHANGELOG.md
As agreed upon at our "_pubsec-declarative-toolkit - Requested Changes for Pull Request #317 Review: Gh4534 - fix linting and enabled linter workflow #317_" collaborative discussion on April 3rd, 2023 (2:00PM EST), the .markdown-lint-config.yaml configuration file was updated to include a 'false' entry for MD012 (Multiple consecutive blank lines). This modification is a workaround to accommodate CHANGELOG.md files that are generated and maintained by release-please.

2023-04-05 14:57 UTC, davelanglois-ssc approved these changes

2023-04-05 14:58 UTC, stephanemillaire-ssc approved these changes

2023-04-05 14:58 UTC, alaincormier-ssc approved these changes

2023-04-05 15:00 UTC, merged