…
ssc-spc-ccoe-cei/gcp-tools pull request #53
Opened 2023-09-12 18:20 UTC by borkodjurkovic-ssc

Changes:

- Updated `setup-kcc.sh`:
  - Added firewall rules for ubuntu OS updates (Allow egress to IP addresses for northamerica-northeast1-a.gce.clouds.archive.ubuntu.com, us-east1.gce.archive.ubuntu.com, security.ubuntu.com)
  - Added project level allow policy to enable VPC peering to Google owned organization. This is required for GKE / Anthos control plane access.
  - Updated Anthos config controller to be a private cluster
  - Removed setting up of `git-creds` and `root-sync`.  Since the config controller cluster is private, this cannot be done at this point.  A bastion host / proxy needs to be first provisioned to enable connectivity to the cluster's private endpoint.
- Added a short README file.

2023-09-13 12:27 UTC, alaincormier-ssc commented on scripts/bootstrap/setup-kcc.sh
>  SA_EMAIL="$(kubectl get ConfigConnectorContext -n config-control \
`SA_EMAIL` is set with the output of `kubectl`, which most likely won't work here with a private cluster?
subsequent commands referencing $SA_EMAIL will most likely fail as well

2023-09-13 12:42 UTC, alaincormier-ssc commented on scripts/bootstrap/setup-kcc.sh
>  SA_EMAIL="$(kubectl get ConfigConnectorContext -n config-control \
a possibility would be to split the script at this point, either in a different file or with functions?
i.e.
1. run script/function until the cluster is created, then stop.
2. operator connects to cluster
3. run script/function to get SA_EMAIL, set IAM permissions, git-creds and root-sync

2023-09-14 11:55 UTC, davelanglois-ssc commented on scripts/bootstrap/README.md
> +bash tools/scripts/bootstrap/configure-kcc-access.sh.sh <PATH TO .ENV FILE>
extra .sh in the script name

2023-09-14 12:01 UTC, davelanglois-ssc commented on scripts/bootstrap/setup-kcc.sh
> +gcloud resource-manager org-policies allow compute.restrictVpcPeering "under:organizations/433637338589" --project "$PROJECT_ID"
we are not supposed to publish  this org id. can you please remove it from here and provide generic instructions in the README about this requirements which only applies to an organization with existing org policies.

2023-09-14 12:04 UTC, davelanglois-ssc requested changes
I like it, please address my comments

2023-09-14 12:06 UTC, alaincormier-ssc commented on scripts/bootstrap/setup-kcc.sh
> +  gcloud anthos config controller create "$CLUSTER" --location "$REGION" --network "$NETWORK" --subnet "$SUBNET" --master-ipv4-cidr-block="172.16.0.128/28" --full-management --man-blocks="192.168.0.0
just thinking, for re-usability purpose, if there would be value in defaulting to private, but keeping a public endpoint as an option? 

something like...
```bash
ENDPOINT='--man-blocks="192.168.0.0/16" --use-private-endpoint'
if [ "$public_endpoint_opt" = true ]; then
  ENDPOINT=''
fi
...
# then add that $ENDPOINT variable at the end of the create commands
gcloud anthos config controller create "$CLUSTER" --location "$REGION" --network "$NETWORK" --subnet "$SUBNET" "$ENDPOINT"

```

2023-09-14 13:33 UTC, davelanglois-ssc commented on scripts/bootstrap/setup-kcc.sh
> +  gcloud anthos config controller create "$CLUSTER" --location "$REGION" --network "$NETWORK" --subnet "$SUBNET" --master-ipv4-cidr-block="172.16.0.128/28" --full-management --man-blocks="192.168.0.0
Yeah, it could be useful for landing zone developpers

2023-09-14 13:47 UTC, borkodjurkovic-ssc commented on scripts/bootstrap/README.md
> +bash tools/scripts/bootstrap/configure-kcc-access.sh.sh <PATH TO .ENV FILE>
Fixed.

2023-09-14 13:47 UTC, borkodjurkovic-ssc commented on scripts/bootstrap/setup-kcc.sh
> +gcloud resource-manager org-policies allow compute.restrictVpcPeering "under:organizations/433637338589" --project "$PROJECT_ID"
Fixed.

2023-09-14 19:17 UTC, borkodjurkovic-ssc commented on scripts/bootstrap/setup-kcc.sh
> +  gcloud anthos config controller create "$CLUSTER" --location "$REGION" --network "$NETWORK" --subnet "$SUBNET" --master-ipv4-cidr-block="172.16.0.128/28" --full-management --man-blocks="192.168.0.0
Added public_endpoint_opt.

2023-09-15 11:02 UTC, alaincormier-ssc approved these changes
LGTM
well done

2023-09-15 12:18 UTC, davelanglois-ssc approved these changes

2023-09-15 12:57 UTC, lucstjean-ssc approved these changes
/lgtm Borko!

2023-09-15 13:11 UTC, merged

2023-09-28 21:14 UTC, fmichaelobrien commented
Validated GKE cluster with public endpoint


## rerun setup-kcc.sh with -p public ip option
see

```
export CLUSTER=kcc-oi2
export REGION=northamerica-northeast1
export PROJECT_ID=kcc-oi2-cluster
export LZ_FOLDER_NAME=kcc-lz-20230928b
export NETWORK=kcc-oi2-vpc
export SUBNET=kcc-oi2-sn

michael@cloudshell:~/kcc-oi/github/gcp-tools/scripts/bootstrap (kcc-oi)$ ./setup-kcc.sh -afp kcc.env

1644 - estimate 1700 kcc-oi2 cluster up
##INFO - Create Config controller

Create request issued for: [kcc-oi2]
Waiting for operation [projects/kcc-oi2-cluster/locations/northamerica-northeast1/operations/operation-1695933801715-606715bd057e8-f452780e-92d1cb2e] to complete...working..
```

fix

```
michael@cloudshell:~/kcc-oi/github/gcp-tools/scripts/bootstrap (kcc-oi)$ ./setup-kcc.sh -afp kcc.env
aiting for operation [projects/kcc-oi2-cluster/locations/northamerica-northeast1/operations/operation-1695933801715-606715bd057e8-f452780e-92d1cb2e] to complete...done.                                    
Created instance [kcc-oi2].
Fetching cluster endpoint and auth data.
kubeconfig entry generated for krmapihost-kcc-oi2.

##INFO - Config controller get credentials

Fetching cluster endpoint and auth data.
kubeconfig entry generated for krmapihost-kcc-oi2.

##WARNING - configure-kcc-access.sh script should be run once connectivity to the cluster is established using bastion host / proxy.
ichael@cloudshell:~/kcc-oi/github/gcp-tools/scripts/bootstrap (kcc-oi2-cluster)$ kubectl get nodes
NAME                                                STATUS   ROLES    AGE     VERSION
gk3-krmapihost-kcc-oi2-default-pool-6fc83c0e-ss20   Ready    <none>   9m12s   v1.27.3-gke.100
gk3-krmapihost-kcc-oi2-pool-1-28f0e374-tzw8         Ready    <none>   3m43s   v1.27.3-gke.100
gk3-krmapihost-kcc-oi2-pool-1-ae2f0850-4kmt         Ready    <none>   7m32s   v1.27.3-gke.100
gk3-krmapihost-kcc-oi2-pool-1-c9c2a582-9sdc         Ready    <none>   2m47s   v1.27.3-gke.100
```
cluster up with no admissions endpoint (has both public and private endpoints)
<img width="1635" alt="Screenshot 2023-09-28 at 5 03 44 PM" src="https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/assets/94715080/303754e9-d75a-4d6a-a06e-ffdc236c29ca">


<img width="1365" alt="Screenshot 2023-09-28 at 5 09 12 PM" src="https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/assets/94715080/34e58e12-9bc3-4828-8760-98dfe361215b">

2023-10-20 05:14 UTC, obriensystems commented
editupdate: found them in the new 2nd scripthttps://github.com/ssc-spc-ccoe-cei/gcp-tools/blob/main/scripts/bootstrap/configure-kcc-access.sh#L35

Issue is that the access script assumes rootsync usage - it leaves out the kpt optionI recommend we put the yakima service account role additions back to the generic setup script.

2023-10-20 16:20 UTC, obriensystems commented
automation test target env root at landing.systems
dev target obrien.enginnering
partial fortigate kcc.landing.systems
pull/run
https://github.com/GoogleCloudPlatform/pubsec-declarative-toolkit/tree/gh446-hub